### PR TITLE
corrections

### PR DESCRIPTION
**Pull request by jaredh159**
@jaredh159 @Henderjay

### CODE REVIEW

**Comment by jaredh159** [comment]
@Henderjay sorry for the ping here, you can ignore this PR. Using it to test the big thing I've been building.  You may get a few more notifications. 😬

**Comment by jaredh159** [comment]
PDF previews (commit ed2ad3e3c50ca6c9af81eb597b4101c99f9782ba):

- [life-and-letters--modernized--11-chapter-11.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--modernized--11-chapter-11.pdf)
- [life-and-letters--original--11-chapter-11.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--original--11-chapter-11.pdf)

**Comment by jaredh159** [comment]
PDF previews (commit ed2ad3e3c50ca6c9af81eb597b4101c99f9782ba):

- [life-and-letters--modernized--11-chapter-11.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--modernized--11-chapter-11.pdf)
- [life-and-letters--modernized.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--modernized.pdf)
- [life-and-letters--original--11-chapter-11.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--original--11-chapter-11.pdf)
- [life-and-letters--original.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--original.pdf)

**Comment by jaredh159** [comment]
PDF (test) previews (commit ed2ad3e3c50ca6c9af81eb597b4101c99f9782ba):

- [life-and-letters--modernized--11-chapter-11.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--modernized--11-chapter-11.pdf)
- [life-and-letters--modernized.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--modernized.pdf)
- [life-and-letters--original--11-chapter-11.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--original--11-chapter-11.pdf)
- [life-and-letters--original.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--original.pdf)

**Comment by FriendsLibrary** [comment]
PDF previews (commit ed2ad3e3c50ca6c9af81eb597b4101c99f9782ba):

- [life-and-letters--modernized--11-chapter-11.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--modernized--11-chapter-11.pdf)
- [life-and-letters--modernized.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--modernized.pdf)
- [life-and-letters--original--11-chapter-11.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--original--11-chapter-11.pdf)
- [life-and-letters--original.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--original.pdf)

**Comment by FriendsLibrary** [comment]
PDF previews (commit ed2ad3e3c50ca6c9af81eb597b4101c99f9782ba):

- [life-and-letters--modernized--11-chapter-11.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--modernized--11-chapter-11.pdf)
- [life-and-letters--modernized.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--modernized.pdf)
- [life-and-letters--original--11-chapter-11.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--original--11-chapter-11.pdf)
- [life-and-letters--original.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--original.pdf)

**Comment by FriendsLibrary** [comment]
PDF previews (commit 390f0066769f306c4f46b8fab1b0a28ff328616b):

- [life-and-letters--modernized--11-chapter-11.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--modernized--11-chapter-11.pdf)
- [life-and-letters--modernized.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--modernized.pdf)
- [life-and-letters--original--11-chapter-11.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--original--11-chapter-11.pdf)
- [life-and-letters--original.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/life-and-letters--original.pdf)

**Comment by ghost** [comment]
PDF previews (commit 6fd467736235f196f35fe449011c007f406cd52a):

- [life-and-letters--modernized--11-chapter-11.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/6fd467736235f196f35fe449011c007f406cd52a/life-and-letters--modernized--11-chapter-11.pdf)
- [life-and-letters--modernized.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/6fd467736235f196f35fe449011c007f406cd52a/life-and-letters--modernized.pdf)
- [life-and-letters--original--11-chapter-11.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/6fd467736235f196f35fe449011c007f406cd52a/life-and-letters--original--11-chapter-11.pdf)
- [life-and-letters--original.pdf](https://friends-library-assets.nyc3.digitaloceanspaces.com/adoc-pr/rebecca-jones/3/6fd467736235f196f35fe449011c007f406cd52a/life-and-letters--original.pdf)

**Pull request merged**
